version: "3.9"
services:
  api-rest:
    build:
      context: .
      dockerfile: Dockerfile.api-rest
    container_name: api-rest
    ports:
      - "8000:8000"
    depends_on:
      - orchestrator
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8003
    networks:
      - a2a-net

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    container_name: orchestrator
    ports:
      - "8003:8003"
    depends_on:
      - agente-pgp
      - agente-clima
    environment:
      - AGENT_URLS=http://agente-pgp:8001,http://agente-clima:8002
    networks:
      - a2a-net

  agente-pgp:
    build:
      context: .
      dockerfile: Dockerfile.pgp-agent
    container_name: agente-pgp
    ports:
      - "8001:8001"
    environment:
      - PGP_AGENT_URL=http://agente-pgp:8001
    networks:
      - a2a-net

  agente-clima:
    build:
      context: .
      dockerfile: Dockerfile.clima-agent
    container_name: agente-clima
    ports:
      - "8002:8002"
    environment:
      - CLIMA_AGENT_URL=http://agente-clima:8002
    networks:
      - a2a-net

networks:
  a2a-net:
    driver: bridge
